# Generated by Django 4.1.3 on 2022-12-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iotapp', '0002_token_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='token',
        ),
    ]
